columns:
  - class: category
  - person_home_ownership: str
  - loan_intent: str
  - loan_grade: str
  - cb_person_default_on_file: str
  
numerical_columns:
  - person_age
  - person_income
  - person_emp_length
  - loan_amnt
  - loan_int_rate
  - loan_status
  - loan_percent_income
  - cb_person_cred_hist_length
  
drop_columns:
